"use client";
import {useEffect,useRef,useState} from 'react';
import {ResultsMediaDialog} from '@/components/media/results-media-dialog';
import {developmentRewardProvider} from '@/lib/rewards/provider';
export function RewardDialog({sessionId,onSuccess,onClose}:{sessionId:string;onSuccess:(receipt:string)=>void;onClose:()=>void}){
  const [mode,setMode]=useState<'loading'|'development'|'unavailable'>('loading'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),controller=useRef<AbortController|null>(null);
  useEffect(()=>{const active=new AbortController();controller.current=active;void fetch('/api/reward/development',{signal:active.signal}).then(r=>r.json()).then(r=>setMode(r.development?'development':'unavailable')).catch(()=>{if(!active.signal.aborted)setMode('unavailable');});return()=>active.abort();},[]);
  const complete=async()=>{if(busy)return;setBusy(true);setMessage('');try{const result=await developmentRewardProvider.request(sessionId,controller.current!.signal);if(result.status==='completed')onSuccess(result.receipt);else setMessage('The reward was not completed. Please try again.');}catch{if(!controller.current?.signal.aborted)setMessage('The reward could not be completed. Please try again.');}finally{setBusy(false);}};
  return <ResultsMediaDialog title="Unlock enhanced memories" onClose={onClose}><p className="media-note">One completed reward unlocks GIF, Live Strip, Full Live Moment and QR sharing for this session. Download Photo is always free.</p>{mode==='loading'?<p role="status">Checking availability…</p>:mode==='unavailable'?<p role="status">Rewards are not available yet. Your photos are safe, and Download Photo is still free.</p>:<><strong>Development reward — no real advertisement</strong><p className="media-note">Local testing only. Complete or simulate a failed reward.</p><button className="button" disabled={busy} onClick={()=>void complete()}>Complete development reward</button><button className="text-link" disabled={busy} onClick={()=>setMessage('Development reward failed. Nothing was unlocked. Try again when ready.')}>Simulate failure</button></>}<p role="status">{message}</p><button className="text-link" onClick={onClose}>Cancel</button></ResultsMediaDialog>;
}
