// Run against the local production build and tests/share-fixture.mjs only.
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {get,request as httpRequest} from 'node:http';
const origin='http://127.0.0.1:3003',fixture='http://127.0.0.1:9006';
await fetch(fixture+'/__test/reset');
const request=(path,options={})=>fetch(origin+path,options);
const issue=await request('/api/reward/development',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({sessionId:crypto.randomUUID(),result:'completed'})});
assert.equal(issue.status,200);const {receipt}=await issue.json();assert.ok(receipt);
const png=await sharp({create:{width:320,height:960,channels:4,background:'#f3e9d2'}}).png().toBuffer();
const upload=(body=png,headers={})=>request('/api/shares',{method:'POST',headers:{Origin:origin,Authorization:'Bearer '+receipt,'Content-Type':'image/png',...headers},body});
assert.equal((await upload(png,{Authorization:''})).status,403);
assert.equal((await upload(png,{Authorization:'Bearer forged'})).status,403);
assert.equal((await upload(png,{Origin:'https://unrelated.example'})).status,403);
assert.equal((await upload(png,{'Content-Type':'video/webm'})).status,400);
assert.equal((await upload(Buffer.from('not a PNG'))).status,400);
const huge=await sharp({create:{width:8193,height:1,channels:3,background:'#000'}}).png().toBuffer();assert.equal((await upload(huge)).status,400);
const create=await upload();assert.equal(create.status,201);const share=await create.json();assert.equal(Date.parse(share.expiresAt)-Date.parse(share.createdAt),600000);assert.match(share.id,/^[a-f0-9]{48}$/);
const image=await request('/api/shares/'+share.id+'/image');assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');assert.match(image.headers.get('cache-control'),/no-store/);assert.equal(image.headers.get('etag'),null);
const pixels=await sharp(Buffer.from(await image.arrayBuffer())).raw().toBuffer();assert.deepEqual([...pixels.slice(0,4)],[243,233,210,255]);
assert.equal((await request('/api/shares/123/image')).status,410);
assert.equal((await request('/api/shares/'+ 'aa'.repeat(24)+'/image')).status,410);
await fetch(fixture+'/__test/advance?ms=600001');assert.equal((await request('/api/shares/'+share.id+'/image')).status,410);
const second=await upload();assert.equal(second.status,201);const next=await second.json();assert.notEqual(next.id,share.id);assert.equal((await request('/api/shares/'+share.id+'/image')).status,410);
const stats=await(await fetch(fixture+'/__test/stats')).json();assert.equal(stats.objects,2,'Expiry must work before physical deletion');
assert.equal((await request('/api/shares/cleanup',{method:'POST'})).status,401);
const cleanup=await request('/api/shares/cleanup',{method:'POST',headers:{Authorization:'Bearer fixture-cleanup-secret'}});assert.equal(cleanup.status,200);assert.equal((await cleanup.json()).removed,1);
assert.equal((await upload()).status,201);assert.equal((await upload()).status,201);assert.equal((await upload()).status,503,'bounded per-session share creation');
await fetch(fixture+'/__test/fail?on=1');assert.equal((await upload()).status,503);await fetch(fixture+'/__test/fail?on=0');
const publicConfig=await new Promise((resolve,reject)=>{get(origin+'/api/reward/development',{headers:{Host:'public.example'}},r=>{let data='';r.on('data',c=>data+=c);r.on('end',()=>resolve(JSON.parse(data)));}).on('error',reject);});assert.equal(publicConfig.development,false);
const publicUpload=await new Promise((resolve,reject)=>{const r=httpRequest(origin+'/api/shares',{method:'POST',headers:{Host:'public.example',Origin:'http://public.example',Authorization:'Bearer '+receipt,'Content-Type':'image/png','Content-Length':png.length}},r=>{r.resume();r.on('end',()=>resolve(r.statusCode));});r.on('error',reject);r.end(png);});assert.equal(publicUpload,403,'development receipt must not authorize public production sharing');
console.log('Sharing HTTP checks passed: authorization, origin, PNG validation, private image delivery, exact TTL, expired denial, fresh IDs, rate bound, cleanup, outage and public-host reward denial.');
await fetch(fixture+'/__test/reset');
