import { ContentPage, ContentSection } from '@/components/content/site-chrome';
import { contentMetadata } from '@/lib/site';
export const metadata = contentMetadata("Terms of use", "The terms for using The Vintage Photobooth, creating local media and sharing temporary strips.", '/terms');
export default function Page(){return <ContentPage title="Terms of use" intro="The terms for using The Vintage Photobooth, creating local media and sharing temporary strips." ads={false} eyebrow="The details"><p className="legal-date">Last updated: 8 October 2026</p><ContentSection title="Using The Vintage Photobooth"><p>These terms apply to your use of The Vintage Photobooth. By using the service, you agree to these terms. If you do not agree, please do not use it. The service is operated under the name The Vintage Photobooth; questions can be sent to <a href="mailto:the.vintage.pb@gmail.com">the.vintage.pb@gmail.com</a>.</p></ContentSection>
<ContentSection title="Your photographs and recordings"><p>You are responsible for the images, text and recordings you create or select. Only use material you have permission to use, and get appropriate permission from people you photograph or record. You retain your rights in your own content.</p><p>Choosing temporary QR sharing permits us and the storage provider to process, store and deliver that finished still strip for the sharing feature. It does not grant us a right to use your photographs in marketing. Local media is processed on your device.</p></ContentSection>
<ContentSection title="Permitted use and misuse"><p>Use the booth for lawful personal or other authorized creative purposes. Do not use it to distribute unlawful content, violate another person’s privacy or intellectual-property rights, impersonate others deceptively, or harass people.</p><p>Do not bypass reward authorization, probe for other people’s share links, abuse upload or download endpoints, introduce malicious files, or disrupt the service. We may restrict abusive requests and suspend affected features to protect users and infrastructure.</p></ContentSection>
<ContentSection title="Downloads, rewards and temporary links"><p>Download Photo is free. Enhanced outputs require a completed reward through a supported provider; the public site does not currently have a live rewarded provider. A future verified reward is intended to unlock the enhanced features together for the current session. Clicking an ordinary display advertisement is never required and does not count as a reward.</p><p>When QR sharing is available, the server stops new access ten minutes after publication. Save files you want to keep. Recipients may retain copies downloaded while a link is active, and expiry cannot remove those copies. We do not provide long-term storage or recovery of local sessions.</p></ContentSection>
<ContentSection title="Site materials and third-party services"><p>The interface, site text and supplied design assets are protected by their applicable intellectual-property rights. Using the editor to create a finished strip does not transfer ownership of the application or its source assets to you. Respect third-party rights when using your output.</p><p>Hosting, temporary storage and advertising rely on third-party services. Their applicable terms and privacy practices also govern their services. Digital filter names and the vintage aesthetic do not imply endorsement by camera or film manufacturers.</p></ContentSection>
<ContentSection title="Availability and device limitations"><p>The service is provided as available, without a promise of uninterrupted operation or compatibility with every browser. Camera permission, microphone permission, available memory, media codecs, network conditions and device performance can affect results. The Print action is an on-screen animation and does not operate a physical printer.</p><p>To the extent permitted by applicable law, we disclaim implied warranties and liability for loss caused by service interruptions, unavailable features or lost unsaved media. Nothing in these terms excludes rights or liabilities that cannot lawfully be excluded. Keep your own copies of important outputs.</p></ContentSection>
<ContentSection title="Changes and contact"><p>Features and these terms may change. Revised terms will be posted here with an updated date; continued use after an update means you accept the revised terms, subject to any rights required by applicable law.</p><p>Contact <a href="mailto:the.vintage.pb@gmail.com">the.vintage.pb@gmail.com</a> for questions about the service or these terms. Our <a href="/privacy">Privacy page</a> explains local processing, temporary sharing and third-party data handling.</p></ContentSection></ContentPage>;}
