import { ContentPage, ContentSection, BoothCTA, EnhancedNotice } from '@/components/content/site-chrome';
import { contentMetadata } from '@/lib/site';
import { FILTER_PRESETS } from '@/lib/filters/presets';
export const metadata = contentMetadata("A strip with your signature", "Explore real photo-strip, filter, frame, text and motion features in The Vintage Photobooth.", '/features');
export default function Page(){return <ContentPage title="A strip with your signature" intro="Explore real photo-strip, filter, frame, text and motion features in The Vintage Photobooth."><ContentSection title="A photo count for the occasion"><p>Keep a single portrait or build a sequence of 2, 4, 5, 6, 8, 10 or 12 photos. Generated frames support all these counts. Larger sequences make room for more expressions, but also use more browser memory—especially with motion recording enabled.</p><p>Camera selection, mirror controls and device-photo uploads let you work with the setup you have. Uploaded images are decoded locally; their format support depends on your browser.</p></ContentSection>
<ContentSection title="Ten looks, from clean to nostalgic"><div className="filter-description-grid">{FILTER_PRESETS.map(filter=><div key={filter.id}><h3>{filter.name}</h3><p>{filter.description}</p></div>)}</div><p>These are original digital looks inspired by the feel of photographic prints. They do not imply affiliation with a camera or film brand. Preview processing adapts to the device; exported stills apply the selected look to the image itself.</p></ContentSection>
<ContentSection title="Frames that fit the memory"><p>Nine generated frame styles work across the supported photo counts. Five illustrated templates add a different character to four-photo strips. Their artwork and transparent windows remain part of the finished composition.</p><p>Choose among sixteen backing colors, and let the frame fit the photos to its slots. A pale backing gives captions room to breathe; a dark one can make bright portraits stand out. The PNG renderer uses the same window geometry as the preview.</p></ContentSection>
<ContentSection title="Stickers, words and small finishing touches"><p>Use the sixteen supplied sticker designs as accents or build a playful border. Move, rotate and resize your decorations; arrange layers to control what sits above what. Text can turn a strip into a date stamp, a message or a keepsake for a particular day.</p><p>Undo and redo support experimentation. Editing invalidates generated outputs so the next download reflects the new composition. Select any photo to reposition or zoom it within its window. Each photo has independent adjustments, and Reset Photo leaves your stickers, text and other photos intact.</p></ContentSection>
<ContentSection title="A countdown with a final pose"><p>Capture Sound supplies countdown, Smile! and shutter cues without turning on your microphone. Smile! marks the final pose second. Choose manual 1-second captures to change poses at your own pace, or a continuous 3-, 5- or 10-second sequence.</p><p>The optional screen flash fills the viewport with white for each camera shutter, with a short delay before reading the video frame. A gentle digital lift also brightens the captured photo while preserving its selected filter. Display light cannot replace a dedicated photographic flash in a dark room.</p></ContentSection>
<ContentSection title="Three ways to keep things moving"><p><strong>GIF:</strong> a looping sequence made from the captured stills, useful when you want each pose to read clearly.</p><p><strong>Live Strip:</strong> recorded camera moments play in the finished strip, including the countdown, with your saved filters and decorations. Photos without recordings remain still.</p><p><strong>Full Live Moment:</strong> a continuous camera recording of the run, without the decorated-strip layout. It is available only when the camera photos share one recording source. Camera interruptions can make this output unavailable.</p><p>Audio is optional. Recording formats and export support vary by browser; still-photo downloads remain available when motion cannot be recorded.</p><EnhancedNotice/></ContentSection>
<ContentSection title="Free stills and deliberate sharing"><p>Download Photo saves a high-resolution PNG without a reward or account. QR sharing, when available, sends only the final PNG to private Supabase storage and stops new access after ten minutes. It never uploads your raw captures, motion or microphone recording.</p><p>A recipient can save a copy while the link is active. Expiration cannot revoke that saved copy. QR uploads have a 4 MB limit; a larger strip can still be downloaded locally at full resolution.</p></ContentSection><BoothCTA/></ContentPage>;}
